/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.functions;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author i14584i
 */
public class select_prod extends javax.swing.JFrame {
functions func = new functions();
double preco2;
double total;
    /**
     * Creates new form select_prod
     */
    public select_prod() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_pesquisar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(102, 51, 0));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 3, true));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setToolTipText("Selecione os produtos");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 690, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/barrinhas-divisorias-cute-kawaii-photoscape-shopping-by-thataschultz20110925-scallop_beige.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 710, 40));

        txt_pesquisar.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        txt_pesquisar.setForeground(new java.awt.Color(204, 204, 204));
        txt_pesquisar.setText("Pesquisar...");
        txt_pesquisar.setToolTipText("Pesquisar");
        txt_pesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_pesquisarMouseClicked(evt);
            }
        });
        txt_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pesquisarKeyTyped(evt);
            }
        });
        getContentPane().add(txt_pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 620, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        jLabel7.setToolTipText("Voltar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 110, 80));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 588, 60, -1));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 100)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Produtos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 340, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search-icon.png"))); // NOI18N
        jLabel2.setToolTipText("Pesquisar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 215, 70, 50));

        jLabel4.setBackground(new java.awt.Color(255, 228, 196));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bg/Fundo bisque.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int linha = jTable1.getSelectedRow();
       String selecionado = jTable1.getValueAt(linha, 0).toString();
       int res = clicar();
       if(res == 0)
       {
           String res2 = select(selecionado);
        if (res2.equals("nao")) {
            preco(selecionado);

            func.execute("INSERT INTO compras VALUES('" + selecionado + "'," + preco2 + ",1);", "INSERT");
            func.execute("UPDATE estoque SET qtd_prod=qtd_prod - 1 WHERE nome_prod='" + selecionado + "';", "INSERT");

            total = total + preco2;
        } else {
            preco(selecionado);
            func.execute("UPDATE compras SET qtd_prod=qtd_prod + 1 WHERE nome_prod='" + selecionado + "';", "INSERT");
            func.execute("UPDATE estoque SET qtd_prod=qtd_prod - 1 WHERE nome_prod='" + selecionado + "';", "INSERT");
            total = total + preco2;
        }
        //jTextField1.setText("R$" + total);
       }
       else if(res == 1)
       {
       }
       else
       {
       }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        caixa frm = new caixa();
        frm.total = total;
        frm.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel12.setText("Voltar");
        ImageIcon img = new ImageIcon("src//Imagens//back-selecionado.png");
        jLabel7.setIcon(img);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel12.setText("");
        ImageIcon img = new ImageIcon("src//Imagens//back.png");
        jLabel7.setIcon(img);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel lista = new DefaultTableModel();
        lista.addColumn("Produto");;
        ResultSet rs = func.execute("SELECT * FROM estoque ORDER BY nome_prod ASC;", "SELECT");
        try {
            while (rs.next()) {
                String nome = rs.getString("nome_prod");
                String[] dados = {nome};
                lista.addRow(dados);
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }

        jTable1.setModel(lista);
    }//GEN-LAST:event_formWindowOpened

    private void txt_pesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pesquisarMouseClicked
        txt_pesquisar.setText("");
        txt_pesquisar.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_pesquisarMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
      
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
      
    }//GEN-LAST:event_jLabel2MouseExited

    private void txt_pesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesquisarKeyTyped

    private void txt_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesquisarKeyReleased
        int qtd = txt_pesquisar.getText().length();

        if (qtd > 1) {
            DefaultTableModel lista = new DefaultTableModel();
            lista.addColumn("Produto");
            functions func = new functions();

            ResultSet rs = func.execute("SELECT * FROM estoque WHERE nome_prod LIKE \"%" + txt_pesquisar.getText() + "%\"", "SELECT");

            try {
                 while (rs.next()) {
                String nome = rs.getString("nome_prod");
                String[] dados = {nome};
                lista.addRow(dados);
            }
                jTable1.setModel(lista);

            } catch (Exception e) {
                System.out.println("" + e);
            }
        }
       else
        {
            DefaultTableModel lista = new DefaultTableModel();
        lista.addColumn("Produto");;
        ResultSet rs = func.execute("SELECT * FROM estoque ORDER BY nome_prod ASC;", "SELECT");
        try {
            while (rs.next()) {
                String nome = rs.getString("nome_prod");
                String[] dados = {nome};
                lista.addRow(dados);
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }

        jTable1.setModel(lista);
        }
    }//GEN-LAST:event_txt_pesquisarKeyReleased

    public void preco(String selecionado) {
        ResultSet rs = func.execute("SELECT * FROM estoque WHERE nome_prod='" + selecionado + "';", "SELECT");
        try {
            while (rs.next()) {
                preco2 = rs.getDouble("preco_prod");
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }
    }

    public String select(String selecionado) {
        String res = "nao";
        ResultSet rs = func.execute("SELECT * FROM compras WHERE nome_prod='" + selecionado + "';", "SELECT");
        try {
            while (rs.next()) {
                res = "sim";
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }
        return res;
    }
    
     public int clicar() {
        int res = 0;
        int i = JOptionPane.showOptionDialog(null,
                "Quantos produtos deseja comprar?",
                "Comprar",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                new String[]{"Somente um", "Mais que um","Cancelar"}, null);
        return i;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_prod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_pesquisar;
    // End of variables declaration//GEN-END:variables
}
